[package]
edition = "2021"
name    = "t03"
version = "0.1.0"

[dependencies]
anyhow    = { workspace = true }
camino    = { workspace = true }
clap      = { workspace = true }
itertools = { workspace = true }
