[package]
edition = "2021"
name    = "t03"
version = "0.1.0"

[dependencies]
anyhow      = { workspace = true }
bon         = { workspace = true }
camino      = { workspace = true }
clap        = { workspace = true }
expect-test = { workspace = true }
itertools   = { workspace = true }
