[workspace]
members  = ["t01", "t02"]
resolver = "2"


[workspace.dependencies]
anyhow      = { version = "1" }
camino      = { version = "1.1" }
clap        = { version = "4.5", features = ["derive"] }
expect-test = "1.5.0"
itertools   = "0.13"
